!function () {
    try {
        var e = "undefined" != typeof window ? window : "undefined" != typeof global ? global : "undefined" != typeof self ? self : {}, t = (new Error).stack;
        t && (e._sentryDebugIds = e._sentryDebugIds || {}, e._sentryDebugIds[t] = "e14fbb3f-c053-4c01-a8ce-51aa2f878d1f", e._sentryDebugIdIdentifier = "sentry-dbid-e14fbb3f-c053-4c01-a8ce-51aa2f878d1f")
    } catch (e) {
    }
}();
var _global = "undefined" != typeof window ? window : "undefined" != typeof global ? global : "undefined" != typeof self ? self : {};
_global.SENTRY_RELEASE = {id: "v9-170-1"}, (self.__LOADABLE_LOADED_CHUNKS__ = self.__LOADABLE_LOADED_CHUNKS__ || []).push([[867], {
    7508: function (e, t, o) {
        o.d(t, {
            Z: function () {
                return s
            }
        });
        o(82526), o(57327), o(41539), o(54747), o(49337);
        var i = o(2321);

        function a(e, t) {
            var o = Object.keys(e);
            if (Object.getOwnPropertySymbols) {
                var i = Object.getOwnPropertySymbols(e);
                t && (i = i.filter((function (t) {
                    return Object.getOwnPropertyDescriptor(e, t).enumerable
                }))), o.push.apply(o, i)
            }
            return o
        }

        function n(e) {
            for (var t = 1; t < arguments.length; t++) {
                var o = null != arguments[t] ? arguments[t] : {};
                t % 2 ? a(Object(o), !0).forEach((function (t) {
                    (0, i.Z)(e, t, o[t])
                })) : Object.getOwnPropertyDescriptors ? Object.defineProperties(e, Object.getOwnPropertyDescriptors(o)) : a(Object(o)).forEach((function (t) {
                    Object.defineProperty(e, t, Object.getOwnPropertyDescriptor(o, t))
                }))
            }
            return e
        }

        const s = new (o(92903).Z)({
            fa: n(n(n(n(n(n(n(n(n(n(n(n(n(n(n(n(n(n(n(n(n(n(n(n(n(n({}, {
                categories: "دسته‌ها",
                cats: "دسته‌ها",
                posts: "آگهی‌ها",
                submitNewPost: " ثبت آگهی ",
                submitPost: "ارسال آگهی",
                identityConfirmation: "تأیید هویت",
                needsToBeVerified: "نیاز به بررسی هویت(اجباری)",
                identityRevoke: "اعلام تغییر مالکیت سیم‌کارت",
                submitPostTitle: "ثبت آگهی",
                report: "گزارش",
                search: "جستجو",
                credit: "ودیعه",
                creditToman: "ودیعه (تومان)",
                rent: "اجاره",
                rentSliderLabel: "برای تبدیل بکشید",
                rentMountlyToman: "اجارهٔ ماهانه (تومان)",
                divarAiSupport: "پشتیبان هوشمند دیوار",
                searchOf: "جستجوی",
                searchCities: "جستجو در شهرها",
                searchNeighborhoods: "جستجو در محله‌ها",
                specifyNeighborhood: "تعیین محل",
                qualityBasedOnDescription: "کیفیت آگهی بر اساس توضیحات",
                postQualityDescription: "برای رسیدن کیفیت آگهی به حد مطلوب(نوار سبز رنگ)، توضیحات کاملی برای آگهی بنویسید.",
                all: "همه",
                select: "انتخاب کنید",
                to: "تا",
                from: "از",
                metaTitle: "دیوار {0} - نیازمندی‌ های رایگان، آگهی‌های خرید، فروش  نو و دست دوم و کارکرده، استخدام و خدمات",
                title: "دیوار",
                metaTitleTemplate: "دیوار - {title}",
                metaDescription: "نیازمندی‌ و ثبت آگهی رایگان رهن، اجاره، خرید، فروش خانه، آپارتمان، استخدام، خرید و فروش خودرو، ماشین صفر نو دست دو کارکرده، موبایل و تبلت نو و کارکرده و دست دو، موتور سیکلت صفر و نو و دست دوم و کارکرده، بازی، خدمات در {0}",
                iran: "ایران",
                support: " پشتیبانی ",
                supportAndRules: "پشتیبانی و قوانین",
                supportTicketFollowUp: "پیگیری درخواست",
                supportTicketFollowUpMobile: "پیگیری درخواست‌های پشتیبانی",
                myAccount: "حساب شخصی",
                resendCode: "ارسال دوبارهٔ کد تأیید",
                editMobileNumber: "تغییر شمارهٔ موبایل",
                emptyFieldPhoneNumber: "وارد کردن شمارهٔ موبایل الزامی است.",
                emptyFieldCode: "کد تأیید را وارد کنید.",
                divar: "دیوار",
                aboutDivar: " دربارهٔ دیوار ",
                divarHistory: "تاریخچه‌ٔ دیوار",
                divarBlog: "اتاق خبر",
                back: "بازگشت",
                bookmarked: "نشان شد",
                unmarked: "بی‌نشان شد!",
                next: "بعدی",
                prev: "قبلی",
                selectCity: "انتخاب شهر",
                selectACityAtLeast: "حداقل یک شهر را انتخاب کنید.",
                beforeCategorySelectCity: "قبل از انتخاب دسته‌بندی، لازم است حداقل یک شهر را انتخاب کنید.",
                beforeSearchSelectCity: "قبل از جستجو، لازم است حداقل یک شهر را انتخاب کنید.",
                andManyOtherCities: "{0} و {1} شهر دیگر",
                areYouSureYouWantChangeYourCities: "شما قبلاً انتخاب کردید فهرست آگهی‌های «{0}» را ببینید، آیا شهر خود را به «{1}» تغییر می‌دهید؟",
                yourCitiesChanged: "شهر شما به {0} تغییر کرد.",
                witchCityOrDistrict: "آگهی شما در کدام شهر یا محله دیوار ثبت شود؟",
                selectANeighborhoodAtLeast: "حداقل یک محله انتخاب کنید.",
                andManyOtherNeighborhoods: "{0} و {1} محلهٔ دیگر",
                selectAField: "یک {0} را انتخاب کنید",
                quickSearchCity: "جست‌و‌جوی سریع نام شهر...",
                enterYourPhoneNumber: "لطفاً شماره تلفن خود را وارد کنید.",
                enterAuthKey: "لطفاً کد تأیید را وارد کنید.",
                send: "ارسال",
                internalError: "خطا در برقراری ارتباط با سرور",
                loading: "در حال دریافت...",
                processing: "در حال پردازش...",
                thereIsNoItem: "در حال حاضر آگهی‌ای وجود ندارد",
                captcha: "کد امنیتی",
                tryAgain: "در دریافت اطلاعات مشکلی پیش آمد. دوباره تلاش کنید.",
                copy: "کپی",
                twitter: "توییتر",
                linkedin: "لینکداین",
                instagram: "اینستاگرام",
                aparat: "آپارات",
                submit: "ارسال",
                zone: "محله",
                city: "شهر",
                no: "نه",
                nope: "خیر",
                searchIn: "جستجو در {0}",
                category: "دسته‌بندی",
                accept: "تأیید",
                reject: "رد",
                skip: "بی‌خیال",
                thisPathLeadsNoWhere: "این راه به جایی نمی‌رسد!",
                notFoundPageTitle: "دیوار | این راه به جایی نمی‌رسد!",
                seemsLikeYouveEnteredAWrongAddress: "به نظر آدرس را اشتباه وارد کرده‌اید.",
                goToLinkForRightPath: "برای پیدا کردن مسیر درست می‌توانید سری به {link} بزنید.",
                noResultDescription: "پیشنهاد می‌کنیم:\nنگارش کلمات خود را بررسی کنید؛\nکلمات کلیدی دیگری را انتخاب کنید.",
                error: "خطا",
                exit: "خروج",
                exitConfirmation: "آیا مایل به خروج از حساب کاربری خود هستید؟",
                loginRequired: "برای دسترسی به این بخش باید وارد دیوار شوید.",
                getContactLoginRequired: "برای دریافت اطلاعات تماس وارد حساب خود شوید.",
                postIsArchived: "آگهی مورد نظر دیگر در سایت وجود ندارد، آگهی‌های مشابه در پایین آمده است.",
                enter: "ورود",
                register: "ثبت",
                timeAndLocation: "{time} در {location}",
                homePage: "صفحهٔ اول دیوار",
                oldUrlsServerError: "آدرس درخواستی شما درست نیست. می‌توانید سری به صفحهٔ اول دیوار بزنید.",
                unknownServerError: "مشکلی پیش آمده است که ما در حال رفع آن هستیم.\nنگران نباشید! به زودی برمی‌گردیم!",
                unknownServerErrorTitle: "دیوار - خطا",
                goneServerError: "دسترسی به این صفحه دیگر امکان‌پذیر نیست.",
                download: "دانلود",
                more: "بیشتر",
                downloadSibAppDiscount: "۵۰هزارتومن تخفیف حق عضویت سیب‌اپ، برای تمام بسته‌ها. فقط مخصوص کاربران دیوار.‌ بدون نیاز به کد تخفیف",
                oldAndroidTitle: "پیشنهاد به کاربران نسخه‌ی قدیمی اندروید",
                oldAndroidSuggesting: "به کاربران نسخه‌های قدیمی اندروید پیشنهاد می‌دهیم برای استفاده‌ی بهتر از امکانات دیوار از وبسایت دیوار به نشانی divar.ir استفاده کنند.",
                goToDivarWebsite: "ورود به وبسایت دیوار",
                show: "نمایش",
                getApp: "دریافت برنامه",
                bugBountyProgram: "گزارش آسیب‌پذیری",
                social: "دیوار در شبکه‌های اجتماعی",
                divarInSocial: "دیوار در {name}",
                contactInfo: "اطلاعات تماس",
                contactInfoWithHiddenChars: "ا‌طلا‌عات‌ ‌تما‌س‌",
                text: "متن",
                items: "{0} مورد",
                noPost: "هیچ آگهی یافت نشد.",
                noItem: "موردی یافت نشد",
                chat: " چت ",
                messageInChat: "پیام در چت",
                phoneIsHidden: "شماره مخفی شده است.",
                newMessage: "پیام جدید",
                copyLink: "کپی لینک",
                copied: "کپی شد!",
                linkCopied: "لینک کپی شد!",
                postLinkCopied: "لینک آگهی کپی شد.",
                slug: "شناسه",
                toman: "تومان",
                attentionToThese: "لطفاً به موارد زیر توجه کنید",
                selectCategory: "انتخاب دسته‌بندی",
                selectDistrict: "انتخاب محله",
                map: "نقشه",
                areYouInThisPlace: "آیا میخواهید آگهی شما در {0} ثبت شود؟",
                locatePinError: "مشخص کردن موقعیت روی نقشه اجباری است.",
                submitMetaTitle: "ثبت آگهی در دیوار",
                submitMetaDescription: "با دیوار آگهی خودت رو رایگان بذار تا میلیون ها نفر مخاطب آگهیت رو ببینن. آگهی املاک، آگهی خودرو، لوازم خانه، استخدام و سایر دسته ها",
                image: "تصویر",
                images: "تصاویر",
                rules: "قوانین",
                retry: "تلاش دوباره",
                description: "توضیحات",
                optional: "اختیاری",
                required: "اجباری",
                callSupport: "تماس با پشتیبانی",
                submitDefaultErrorMessages: {maxItems: "تعداد ورودی‌ها نباید بیشتر از {0} باشد.", minItems: "تعداد ورودی‌ها نباید کمتر از {0} باشد", maxLength: "طول متن بیش از حد مجاز بوده و باید کمتر از {0} کاراکتر باشد.", minLength: "طول متن کمتر از حد مجاز است. حداقل تعداد مجاز {0} کاراکتر است.", format: "شکل ورودی نادرست است، لطفاً داده را مطابق نوع فیلد وارد کنید.", maximum: "مقدار این فیلد باید کمتر از {0} باشد.", minimum: "مقدار این فیلد باید بیشتر از {0} باشد.", pattern: "محتوای ورودی نادرست است.", required: "وارد کردن فیلد «{0}» اجباری است.", thisIsRequired: "وارد کردن این مورد الزامی است.", type: "نوع ورودی نادرست است.", uniqueItems: "محتوای ورودی نباید تکراری باشد.", enum: "مقداری ورودی باید یکی از گزینه‌های موجود باشد.", locationNotValid: "مکان انتخاب‌شده خارج از محدودهٔ شهر آگهی است", locationOutOfCountry: "مکان انتخاب شده خارج از کشور است."},
                continue: "ادامه",
                close: "بستن",
                yes: "بله",
                yesChange: "بله، تغییر می‌دهم",
                removePin: "حذف موقعیت",
                removeImage: "حذف تصویر",
                setMainImage: "تصویر اصلی",
                filesDidNotUpload: "فایل‌های زیر به دلیل فرمت نامعتبر یا حجم بالا بارگذاری نشد:",
                fileDeletedBecause: "فایل {0} بارگذاری نشد. {1}",
                requestEntityTooLarge: "حجم فایل بیشتر از حد مجاز است.",
                submitNetworkError: "ارتباط شما با سرور‌های دیوار برقرار نشد. لطفاً دوباره تلاش کنید.",
                searchError: "در دریافت فهرست مشکل پیش آمد.",
                other: "متفرقه",
                captchaNotSolved: "مقدار ورودی نادرست بود! دوباره تلاش کنید.",
                email: "ایمیل",
                phone: "شمارهٔ تلفن",
                phoneWithValue: "تلفن {0}",
                exitWarningTitle: "خروج از دیوار",
                exitWarningConfirm: "تأیید",
                defaultExitWarn: "با کلیک روی این لینک از دیوار خارج می‌شوید.",
                saveChanges: "ثبت تغییرات",
                saveEdited: "ذخیرهٔ تغییرات",
                confirmNumber: "کد تأیید ۶ رقمی",
                phoneNumber: "شمارهٔ موبایل",
                signIn: "ورود",
                enterAuthPhoneTitle: "شمارهٔ موبایل خود را وارد کنید",
                enterAuthPhoneMessage: "برای استفاده از امکانات دیوار، لطفاً شمارهٔ موبایل خود را وارد کنید. کد تأیید به این شماره پیامک خواهد شد.",
                submitEnterAuthPhoneMessage: "قبل از ثبت آگهی، لطفاً وارد حساب خود شوید.\nکد تأیید به این شماره پیامک می‌شود.",
                enterAuthCodeTitle: "کد تأیید را وارد کنید",
                enterAuthCodeMessage: "کد پیامک‌شده به شمارۀ «{phone}» را وارد کنید.",
                sendingAuthCodeMessage: "کد تأیید به شماره موبایل شما ارسال می‌شود. لطفاً کمی صبر کنید.",
                authConditionAcceptance: "{termsOfService} و {privacy} دیوار را می‌پذیرم.",
                privacy: "حریم خصوصی",
                termsOfService: "شرایط استفاده از خدمات",
                requestResendCodeTimer: "درخواست مجدد {timer}",
                requestResendCode: "درخواست کد",
                getContactBlockedTitle: "محدودیت نمایش اطلاعات تماس",
                getContactBlockedText: "دسترسی شما به اطلاعات تماس آگهی‌های دیوار موقتاً محدود شده است.",
                getContactLoginText: "لطفاً جهت دسترسی به اطلاعات تماس آگهی ابتدا وارد دیوار شوید.",
                okay: "باشه",
                confirm: "تأیید",
                cancel: "انصراف",
                confirmAndContinue: "تأیید و ادامه",
                filters: "فیلترها",
                filtersWhenHasValue: "فیلتر",
                notes: "یادداشت‌ها",
                removeFilters: "حذف فیلتر‌ها",
                remove: "حذف",
                applyAllFilters: "اعمال فیلترها",
                deleteAll: "حذف همه",
                loginToManage: "برای مشاهده و مدیریت آگهی‌ها، وارد حساب کاربری خود شوید.",
                authTitle: "ورود به حساب کاربری",
                authVerifyTitle: "تأیید شمارهٔ موبایل",
                postState: "وضعیت آگهی",
                viewPost: "نمایش آگهی",
                managePost: "مدیریت آگهی",
                noSubmittedPostsYet: "در حال حاضر آگهی ثبت‌شده ندارید.",
                address: "نشانی",
                management: "مدیریت",
                personalSubmit: "آگهی شخصی",
                publishInPersonalPage: "انتشار در آگهی‌های شخصی",
                bookmarkLoginText: "با ورود به حساب کاربری، آگهی‌هایی که نشان می‌کنید در حساب کاربری‌ شما ذخیره خواهند شد و از طریق همه دستگاه‌هایی در دسترس خواهند بود که به وسیله آن‌ها وارد حساب کاربری خود در دیوار شوید.",
                notNow: "الان نه",
                doNotAskAgain: "دیگه نپرس",
                dynamicSelect: {manual: "انتخاب دستی", auto: "جستجو"},
                selectARoute: "لطفاً یکی از گزینه‌های منوی سمت راست را انتخاب کنید.",
                noSearchResult: "نتیجه‌ای برای جستجوی شما پیدا نشد.",
                searchPlacesDescription: "پیشنهاد می‌کنیم:\nنگارش کلمات خود را بررسی کنید؛\nنام محله یا خیابان مورد نظر خود را جستجو کنید؛\nدر صورتی ک خیابان مورد نظر شما در نتایج نبود، نزدیک‌ترین خیابان اصلی به آن را جستجو کنید.",
                pleaseLoginToUseFeature: "برای ادامهٔ استفاده از دیوار، نیاز است وارد حساب خود شوید.",
                loginFirst: "پیش از ادامهٔ این فعالیت باید وارد شوید.",
                searchInAllAds: "جستجو در همهٔ آگهی‌های دیوار",
                noSelectOption: "گزینه‌ای نیست",
                topCities: "شهرهای پربازدید",
                allCities: "همهٔ شهرها",
                yourPostInDivar: "آگهی شما در دیوار",
                termsAndConditions: "قوانین و مقررات",
                acceptRules: "با قوانین موافقم",
                rejectRules: "موافق نیستم",
                postNoteHint: "یادداشت تنها برای شما قابل دیدن است و پس از حذف آگهی، پاک خواهد شد.",
                yourNote: "یادداشت شما...",
                addNote: "افزودن یادداشت",
                retryRequest: "درخواست دوباره",
                baladMaps: "دیدن این نقطه روی نقشه و مسیریاب بلد",
                yourLocationIsUnknown: "موقعیت شما نامشخص است.",
                thisPostHasNoImage: "این آگهی عکس ندارد!",
                careers: "فرصت‌های شغلی",
                feedback: "بازخورد",
                submitFeedback: "ثبت",
                in: "در",
                blacklistAppeal: "اعتراض به مسدودی",
                userProfileBanned: "حساب کاربری مسدود",
                changeSimOwnerShip: "تغییر مالکیت سیم‌کارت",
                feedbackSubmissionSucceeeded: "بازخورد شما ارسال شد. ممنون از شما.",
                helpImprovePost: "کمک به بهبود قیمت و اطلاعات آگهی",
                reportBetterPostPrice: "گزارش قیمت مناسب‌تر از این کالا",
                postImagesFeedback: "بازخورد دربارهٔ عکس‌های آگهی",
                postDescriptionFeedback: "بازخورد دربارهٔ توضیحات آگهی",
                sendFeedback: "ارسال بازخورد",
                maxImageUpload: "تعداد عکس‌های انتخاب شده نباید بیشتر از {maxItems} باشد.",
                reset: "بازنشانی",
                evaluationMethod: "نحوهٔ ارزیابی قیمت در دیوار",
                mostSearchedItems: "بیشترین جستجوهای دیوار",
                offlineSyncMessage: "نشان‌ها و یادداشت‌های شما فقط روی این دستگاه در دسترس است",
                sharePage: "به اشتراک‌گذاری",
                manualOptionHint: "وارد کردن مقدار دلخواه",
                manualOptionPlaceholder: "مقدار دلخواه",
                understood: "متوجه شدم",
                youHaveBeenLoggedIn: "شما وارد حساب کاربری خود شدید.",
                noPostsQuote: "هیچ آگهی‌ای در پنل شما ثبت نشده‌است. یک آگهی ثبت کنید.",
                noPostsAction: "ثبت آگهی در دیوار",
                rial: "ریال",
                update: "به‌روزرسانی",
                updateAvailable: "دیوار آمادهٔ به‌روزرسانی است.",
                loggedIn: "با موفقیت وارد شدید.",
                loggedOut: "شما از حساب خود خارج شدید.",
                onLoginAskPushPermission: "با موفقیت وارد شدید. برای دریافت نوتیفیکیشن‌های چت دیوار، لازم است در پیامی که روی مرورگر شما ظاهر می‌شود، دکمه Allow را بزنید.",
                askPushPermission: "برای دریافت نوتیفیکیشن‌های چت دیوار، لازم است در پیامی که روی مرورگر شما ظاهر می‌شود، دکمه Allow را بزنید.",
                askPermissionWithUnreadChat: "در چت پیام نخوانده دارید و برای دریافت نوتیفیکیشن‌های چت دیوار، لازم است در پیامی که روی مرورگر شما ظاهر می‌شود، دکمه Allow را بزنید.",
                shortcutHint: "با زدن دکمهٔ «/» هم می‌توانید جستجو کنید.",
                selectedCustomItems: "{0}‌های انتخاب‌شده",
                selectedItems: "موارد انتخاب‌شده",
                selectAnItemAtLeast: "حداقل یک مورد را انتخاب کنید",
                selectACustomItemAtLeast: "حداقل یک {0} را انتخاب کنید",
                businesses: "کسب‌وکارها",
                postWontRemove: "آگهی شما حذف نخواهد شد.",
                yourIdentityHasConfirmed: "هویت شما تأیید شد.",
                yourIdentityHasRevoked: "تأیید هویت شما در دیوار لغو شد.",
                attention: "توجه",
                identityRevokeConfirmation: "با اعلام «تغییر مالکیت سیم‌کارت»، همهٔ آگهی‌های این حساب کاربری ({phone}) غیرفعال می‌شود.",
                checkConnection: "اتصالتان به اینترنت را بررسی کنید",
                backOnline: "اتصال برقرار شد",
                call: "تماس",
                divarGeneralTermsPage: "صفحهٔ شرایط و قوانین کلی استفاده از دیوار",
                showCategoryGuide: "نمایش راهنمای دسته‌بندی",
                secureCallHelp: "راهنمای تماس ناشناس",
                goToContactInfo: "برو به اطلاعات تماس",
                install: "نصب",
                rejectedPostAppealDescription: "اعتراض ثبت شده توسط کاربر درپنل ساپورت",
                installDivarWebApp: "نصب وب‌اپلیکیشن دیوار",
                installDivarIosApp: "The Wall: See and Buy",
                installDivarIosAppDescription: "نسخهٔ جدید دیوار در اپ استور اپل",
                easyAccessToDivar: "دسترسی آسان‌تر به دیوار از صفحه‌ اصلی",
                saveSearchErrorMessage: "خطایی در نشان کردن جستجو پیش آمد.",
                saveSearchTemporaryDownErrorMessage: "امکان نشان کردن جستجو موقتاً غیرفعال است، لطفا دقایقی دیگر امتحان کنید.",
                onboardingBookmarkSearch: "از این‌جا می‌توانید جستجوهای خود را ذخیره کنید.",
                organizationAddress: "آدرس پستی: تهران، بلوار میرداماد، تقاطع نلسون ماندلا(جردن)، ساختمان ۴۰۴، طبقهٔ ۵",
                seeAllDivarCategories: "دیدن تمام دسته‌های دیوار",
                whatAreYouLookingFor: "چه چیزی آگهی می‌کنید؟",
                searchCategoriesPlaceholder: "مثلاً: اجارهٔ مسکونی، پراید، مبل، کیف و...",
                noAppealablePost: "آگهی برای اعتراض وجود ندارد",
                categorySearchNoResult: "برای جستجوی شما دسته‌ای پیدا نشد. در فهرست زیر دستهٔ درست را انتخاب کنید.",
                selectPostCategoryBySearch: "با جستجو در کادر زیر، دستهٔ آگهی را انتخاب کنید.",
                wallet: "کیف پول",
                allocateQuota: "تخصیص سهمیه",
                submitYourObjection: "اعتراض شما ثبت شد.",
                notifyAppealResult: "نتیجهٔ‌ بررسی طی ۲ ساعت کاری از طریق پیامک و پستچی به شما اعلام می‌شود.",
                yourRejectedPosts: "آگهی‌های رد شدهٔ شما",
                selectRejectedPost: "برای اعتراض به رد آگهی، آگهی مورد نظرتان را انتخاب کنید.",
                appealPost: "اعتراض به رد آگهی",
                noItemToSee: "موردی برای نمایش وجود ندارد",
                searchHistoryError: "خطایی در نمایش جستجو‌های اخیر و نشان شده پیش آمد.",
                divarAppearanceSettings: "تنظیمات ظاهر دیوار",
                settings: "تنظیمات",
                recommendationPostsDescription: "با انتخاب این گزینه، دیوار بر اساس تاریخچهٔ جستجوها و بازدیدهای اخیرتان، به شما آگهی‌هایی را پیشنهاد می‌دهد.",
                seeRecommendationPosts: "دیدن آگهی‌های پیشنهادی",
                recommendationPosts: "آگهی‌های پیشنهادی",
                lightAndDarkMode: "حالت روز و شب",
                changeAppearanceDescription: "می‌توانید ظاهر دیوار را متناسب با سلیقه خود به روز و شب تغییر دهید.",
                lightMode: "حالت روز",
                darkMode: "حالت شب",
                systemDefaultMode: "متناسب با سیستم",
                searchInCategories: "جستجو در دسته‌ها...",
                noCategoryForThisSearch: "هیچ دسته‌ای برای «{0}» وجود ندارد.",
                internalErrorMessage: "ارتباط برقرار نشد.",
                internalErrorDescription: "متأسفانه در دریافت اطلاعات مشکلی پیش آمد. لطفاً دوباره تلاش کنید.",
                chatAndCall: "چت و تماس",
                chooseYourLanguage: "زبان خود را انتخاب کنید",
                enterOTP: "کد امنیتی را وارد کنید",
                OTPInstructions: "برای دسترسی به اطلاعات تماس آگهی‌گذار، لطفاً کد امنیتی که به شمارهٔ شما ارسال شده است را وارد کنید.",
                OTPPlaceholder: "کد امنیتی",
                resendRequest: "درخواست مجدد",
                noAccessToOTP: "دسترسی به کد امنیتی ندارید؟",
                submitOTP: "ثبت کد امنیتی",
                tooManyOTPAttempts: "بیش از حد مجاز برای ثبت کد امنیتی تلاش کرده‌اید. لطفاً حداقل ۲۴ ساعت بعد دوباره تلاش کنید.",
                invalidOTP: "کد امنیتی اشتباه است.",
                doRemove: "حذف کردن",
                showContinue: "نمایش ادامه",
                high: "بالا",
                low: "پایین",
                fair: "منصفانه",
                otpActionsLabel: "اقدامات مربوط به کد امنیتی",
                closeModal: "بستن مودال",
                allCategories: "همهٔ آگهی‌های {0}",
                clear: "پاک کردن",
                categoryNotFound: "دستهٔ مورد نظرم را پیدا نمی‌کنم",
                removeMinimumPrice: "حذف مقدار حداقل",
                removeMaximumPrice: "حذف مقدار حداکثر",
                prevImage: "تصویر قبلی",
                nextImage: "تصویر بعدی",
                imageIndexLabel: "تصویر {0} از {1}",
                openFullScreenGallery: "باز کردن گالری به صورت تمام‌صفحه",
                changeCategory: "تغییر دسته",
                note: "یادداشت",
                postCategory: "دستهٔ آگهی",
                copySomething: "کپی کردن {0}",
                inCategory: "در دستهٔ {category}",
                pleaseWait: "لطفا چند لحظه منتظر باشید",
                foreignersWallet: {title: "کیف پول من", subtitle: "ویژه اتباع"},
                noteDeleted: "یادداشت حذف شد.",
                bookmarkDeleted: "نشان حذف شد.",
                showLocationInNavigator: "نمایش موقعیت در مسیریاب",
                locationOnMap: "موقعیت مکانی",
                chooseOr: "انتخاب یا",
                deleteLabel: "حذف کردن {label}"
            }), {home: {metaTitle: "دیوار: بزرگترین سایت نیازمندی های رایگان در ایران", metaDescription: "دیوار مرجع اصلی نیازمندی های رایگان و خرید و فروش کالای نو و دست دوم. نیازمندی های املاک، خودرو، استخدام، لوازم خانه، خدمات و سایر بخش های مورد نظر شما", description: "دﯾﻮار، ﭘﺎﯾﮕﺎه ﺧﺮﯾﺪ و ﻓﺮوش ﺑﯽ‌واﺳﻄﻪ‌!\nاﮔﻪ دﻧﺒﺎل ﭼﯿﺰی ﻫﺴﺘﯽ، ﺷﻬﺮت رو اﻧﺘﺨﺎب ﮐﻦ و ﺗﻮ دﺳﺘﻪ‌ﺑﻨﺪی‌ﻫﺎ ﺑﻪ دﻧﺒﺎﻟﺶ ﺑﮕﺮد. اﮔﺮ ﻫﻢ ﻣﯽ‌ﺧﻮای ﭼﯿﺰی ﺑﻔﺮوﺷﯽ، ﭼﻨﺪ ﺗﺎ ﻋﮑﺲ ﺧﻮب ازش ﺑﮕﯿﺮ و آﮔﻬﯿﺖ رو ﺑﭽﺴﺒﻮن ﺑﻪ دﯾﻮار.", searchCity: "جستجوی شهر", linksTitles: {submit: "ثبت آگهی", about: "دربارهٔ دیوار", download: "دریافت برنامه", support: "پشتیبانی"}}}), {
                browse: {
                    searchEmptyTitle: "نتیجه‌ای با مشخصات مورد نظر شما پیدا نشد.",
                    changePostsSorting: "از اینجا ترتیب نمایش لیست را تغییر دهید.",
                    goToPostsList: "برو به لیست آگهی‌ها",
                    shortCuts: "میان‌بُر‌های صفحه‌کلید",
                    loadMore: "آگهی‌های بیشتر",
                    seeMore: "نمایش بیشتر",
                    changeCityInputTooltip: "از اینجا می‌توانید شهر خود را تغییر دهید.",
                    viewMoreItems: "مشاهدۀ موارد بیشتر",
                    withChat: "با امکان چت",
                    withTransformablePrice: "با امکان معاوضه",
                    requestTimeTooLong: "خطایی هنگام دریافت اطلاعات رخ داد. لطفاً لحظاتی بعد دوباره تلاش کنید.",
                    inSeconds: "در {0} ثانیه",
                    retryIn: "تلاش دوباره {0}"
                }
            }), {staticPageMeta: {"/terms/employer": {title: "دیوار | شرایط و ضوابط استفاده از سامانه استخدامی دیوار", description: "سامانه استخدامی دیوار با هدف ارائه خدمات به کارفرمایان و کارجویان طراحی شده و تحت شرایط و ضوابطی خدمات مربوطه در حوزه کاریابی را به کاربران ارائه می نماید"}}}), {
                manage: {
                    preview: "پیش‌‌نمایش",
                    previewAndStats: "پیش‌نمایش و آمار",
                    edit: "ویرایش",
                    customersFeedback: "بازخورد بازدیدکنندگان",
                    pay: "پرداخت",
                    promote: "ارتقا",
                    postLink: "لینک آگهی",
                    postPromotion: "ارتقای آگهی",
                    deletePost: "حذف آگهی",
                    postPreview: "پیش‌نمایش آگهی",
                    verifyNumber: "تأیید شماره",
                    requestConfirm: "درخواست تأیید اطلاعات آگهی",
                    postStats: "آمار آگهی",
                    postStatsDesc: "آمار تعداد بازدید روزانه آگهی شما از زمان انتشار آگهی در این نمودار قابل مشاهده است.",
                    notAvailable: "غیرفعال",
                    payWithShetabCards: "پرداخت از طریق کارت‌های شتاب",
                    payPrice: "پرداخت مبلغ {0}",
                    paymentSum: "مبلغ قابل پرداخت",
                    paid: "پرداخت شده",
                    toPaySum: "قابل پرداخت: {0}",
                    selectOnePackage: "یکی از بسته‌ها را انتخاب کنید.",
                    specifyDeleteReason: "علت حذف آگهی را مشخص کنید.",
                    serviceAddedToPost: "سرویس به آگهی اضافه شد.",
                    deleteReasonFetchProblem: "اشکال در دریافت دلایل حذف",
                    timeRemainingToPaymentActivated: "{0} تا فعال شدن پرداخت",
                    postPaymentsList: "لیست پرداخت‌های انجام شده برای این آگهی",
                    previousPayments: "پرداخت‌های قبلی",
                    rowNumber: "ردیف",
                    time: "زمان",
                    costName: "نام هزینه",
                    cost: "هزینه",
                    serviceType: "نوع سرویس",
                    yourServicePurchased: "سرویس موردنظر شما خریداری شد.",
                    paymentMethod: "شیوهٔ پرداخت",
                    paymentId: "شناسهٔ پرداخت",
                    price: "مبلغ",
                    authenticate: "تأیید هویت",
                    nationalIdTip: "کد ملی باید متعلق به مالک شمارهٔ موبایلی باشد که آگهی با آن ثبت شده است.",
                    nationalIdPlaceholder: "۱۲۳۴۵۶۷۸۹۰",
                    emptyNationalId: "وارد کردن کد ملی الزامی است.",
                    wrongNationalId: "کد ملی وارد شده صحیح نیست.",
                    nationalIdDigitOnly: "فقط وارد کردن اعداد (۰ تا ۹) مجاز است.",
                    nationalIdMaxLength: "تعداد ارقام وارد شده بیشتر از ارقام کد ملی است.",
                    nationalIdMinLength: "تعداد ارقام وارد شده کمتر از ارقام کد ملی است.",
                    enterNationalId: "کد ملی خود را وارد کنید.",
                    nationalIdVerified: "کد ملی شما تأیید شد.",
                    totalViews: "بازدید کلی: {0}",
                    today: "امروز",
                    totalViewStatistics: "آمار کل بازدید",
                    todayViewCount: "تعداد بازدید امروز {0}",
                    clickToViewStatisticsDetails: "تعداد بازدیدکنندگان روزانهٔ آگهی شما با ارتقای آگهی افزایش خواهدیافت.\n    برای مشاهدهٔ جزئیات بازدید روزانهٔ آگهی از زمان انتشار، کلیک کنید.",
                    yourDailyViewIsInChart: "آمار بازدید روزانه آگهی شما از زمان انتشار آگهی در این نمودار قابل مشاهده است.",
                    promoteIsDone: "ارتقا آگهی انجام شد.",
                    paymentCaption: "پرداخت از طریق کارت‌های شتاب انجام‌پذیر است.",
                    enterAuthCodeMessage: "کد پیامک‌شده به شمارۀ «{phone}» را وارد کنید. شما این شماره را در آگهی ثبت کردید.",
                    viewPost: "مشاهدهٔ آگهی",
                    postWillRemove: "آگهی تا حداکثر ۳ ساعت دیگر حذف خواهد شد.",
                    payablePrice: "قابل پرداخت: {0}",
                    phishingDescription: "پیامک‌های دیوار با نام Divar ارسال می‌شوند و باقی شماره‌ها نامعتبرند."
                }
            }), {managementMenu: {divarUser: "کاربر دیوار", myPosts: "آگهی‌های من", myPaymentsAndCredit: "پرداخت‌ها و اعتبار من", notes: "یادداشت‌ها", recentVisits: "بازدیدهای اخیر", loginToUse: "برای استفاده از تمام امکانات دیوار وارد حساب خود شوید.", login: "ورود به حساب کاربری", myPayments: "پرداخت‌های من"}}), {payment: {wasUnsuccessful: "پرداخت شما با مشکل مواجه شد.", wasSuccessful: "پرداخت شما با موفقیت انجام شد.", backToDivar: "بازگشت به دیوار", backToDivarToContinue: "برای ادامهٔ فرایند، لطفاً به دیوار بازگردید.", supportPaymentHelp: "در صورت نیاز به راهنمایی می‌توانید از {0} استفاده کنید.", paymentHistory: {timeWindow: "بازهٔ زمانی: {0}", downloadPaymentsHistory: "دانلود همهٔ پرداخت‌های {0}", PaymentHistoryCsvFileName: "پرداخت‌های {0}.csv"}}}), {
                myDivar: {
                    title: " دیوار من ",
                    divarUser: "کاربر دیوار",
                    phone: "تلفن",
                    metaTitle: "صفحه حساب شخصی شما در سایت دیوار",
                    metaDescription: "در این بخش سایت صفحه حساب شخصی خود را در سایت دیوار مشاهده کنید",
                    myPosts: {title: "آگهی‌های من", metaTitle: "دیوار من: آخرین بازدیدها، آگهی های نشان شده و شخصی شما", metaDescription: "دیوار من جایی است که شما می توانید آخرین بازدیدهای خود، آگهی های که نشان کردید و یا در دیوار منتشر کرده اید را ببینید"},
                    bookmarks: {title: "نشان‌ها", revert: "بازگرداندن", cancelDelete: "انصراف", delete: "نشان آگهی حذف شد.", confirmDelete: "بله، حذف کن", deletePermission: "از حذف نشان آگهی مطمئنید؟", metaTitle: "آگهی های نشان شده شما در سایت دیوار", metaDescription: "در این بخش سایت آگهی های نشان شده خود را در سایت دیوار مشاهده کنید", emptyHint: "برای نشان‌کردن آگهی‌ها از دکمهٔ {icon} در صفحهٔ آگهی استفاده کنید."},
                    recentVisits: {title: "بازدیدهای اخیر", metaTitle: "بازدیدهای اخیر شما در سایت دیوار", metaDescription: "در این بخش سایت بازدید های اخیر خود را در سایت دیوار مشاهده کنید", noVisits: "اخیراً از هیچ آگهی‌ای بازدید نکرده‌اید."},
                    auth: {askToLogin: "برای احراز هویت خود در دیوار، وارد حساب کاربری خود شوید.", submitLabel: "ثبت درخواست"},
                    myNotes: {title: "یادداشت‌ها", revert: "بازگرداندن", deleteMessage: "یادداشت حذف شد.", metaTitle: "یادداشت‌های شما در سایت دیوار", metaDescription: "در این بخش سایت یادداشت‌های خود را در سایت دیوار مشاهده کنید", emptyHint: "برای یادداشت گذاشتن روی آگهی‌ها می‌توانید از دکمهٔ {icon} در صفحهٔ آگهی استفاده کنید."},
                    login: {title: "ورود به حساب کاربری", description: "برای استفاده از تمام امکانات دیوار وارد حساب خود شوید."},
                    oAuth: {title: "ورود به حساب کاربری", invalidSource: "منبع احراز هویت نامشخص است.", redirecting: "درحال انتقال به آدرس موردنظر هستید..."},
                    myPayments: {title: "همه پرداخت‌های من", invoiceIssued: "درخواست صدور فاکتور ثبت شد.", paymentInfo: "جزئیات پرداخت", issueInvoice: "درخواست صدور فاکتور", emptyState: "شما تاکنون پرداختی در دیوار انجام نداده‌اید.", finalUser: "اشخاص حقیقی", taxPayer: "اشخاص حقوقی", sidebarTitle: "پرداخت‌های من", metaTitle: "پرداخت‌های شما در سایت دیوار", metaDescription: "در این بخش سایت پرداخت‌های خود را در سایت دیوار مشاهده کنید", chooseUserType: "مشخص کنید فاکتور را برای چه شخصی می‌خواهید.", submitIssueInvoice: "صدور فاکتور"},
                    carPricesEvaluation: "ارزیابی قیمت",
                    thisCar: "این خودرو",
                    myWallet: {noAccess: "شما به این بخش دسترسی ندارید"}
                }
            }), {postSubmit: {selectCategory: "دستهٔ آگهی را انتخاب کنید", goBack: "بازگشت به همهٔ {category}", categories: "دسته‌ها", preLoadSubmitData: "شما در حال ثبت آگهی در دستهٔ «{category}» بوده‌اید. آیا مایل به ادامهٔ آن هستید؟", editCategory: "تغییر دسته‌بندی", subCategories: "زیردسته‌های {category}", location: {cityArea: "محدودهٔ آگهی: {city}", cityAndNeighborhoodArea: "محدودهٔ آگهی: {city}، {neighborhood}", approximateText: "موقعیت دقیق نمایش داده نشود.", searchPlaceholder: "جستجوی شهر، محله، خیابان...", noSearchResult: "نتیجه‌ای برای جستجوی شما پیدا نشد.", noDistrictError: "شهر (محله) موردنظر پیدا نشد.", changeNeighborhoodNotAllowed: "امکان تغییر محله وجود ندارد.", changeCityNotAllowed: "امکان تغییر شهر وجود ندارد."}, imageUpload: "بارگذاری عکس"}}), {
                downloadPage: {
                    pretitle: "جستجو در میان هزاران آگهی",
                    title: "دریافت برنامهٔ دیوار",
                    description: "برنامه را در گوشی خود نصب کنید، کالای موردنظرتان را پیدا کنید یا آگهی رایگان ثبت کنید.",
                    cafeBazaar: "کافه‌بازار",
                    googlePlay: "گوگل‌پلی",
                    androidDirect: "دریافت مستقیم اندروید",
                    appStore: "اپل‌استور",
                    annardooni: "اناردونی",
                    iApps: "آی‌اپس",
                    appStar: "اپ‌استار",
                    sibApp: "سیب‌اپ",
                    sibIrani: "سیب ایرانی",
                    sibche: "سیب‌چه",
                    deviceImg: "اپلیکیشن دیوار در گوشی‌های اندروید",
                    metaTitle: "دانلود اپلیکیشن دیوار | به جمع میلیونی کاربرهای دیوار بپیوندید",
                    metaDescription: "دانلود آخرین نسخه برنامه دیوار(بستر خرید و فروش بی‌واسطه) برای هر دو پلتفرم اندروید (Android) و آی‌اواس (iOS)."
                }
            }), {
                jobs: {
                    manage: {landLineTabText: "افزودن شمارهٔ ثابت", authenticateLandLineTitle: "شمارهٔ ثابت را وارد کنید", authenticateLandLineDescription: "کد تأییدی در تماس با این شماره اعلام می‌شود. پس از تأیید، این شماره در آگهی شما نمایش داده می‌شود.", authenticateLandLineInputPlaceholder: "شمارهٔ ثابت (با پیش‌شمارهٔ شهر)", validateLandLineTitle: "کد تأیید شمارهٔ ثابت را وارد کنید", validateLandLineDescription: "لطفاً کد تأییدی را که در تماس با شمارهٔ {inputLandLinePhone} اعلام می‌شود، وارد کنید.", validateIntervalCooldownText: "درخواست مجدد در {intervalCooldown} ثانیه", validateLandLineInputPlaceholder: "کد تأیید شمارهٔ ثابت", validateSuccessText: "شمارهٔ تلفن ثابت به آگهی اضافه شد."},
                    panel: {
                        postsManagement: "مدیریت آگهی‌ها",
                        employerPanel: "پنل استخدام",
                        bulkLadderTitle: "نردبان گروهی آگهی‌ها",
                        ladderConfirm: "شما {numOfPosts} آگهی را برای نردبان کردن انتخاب کرده‌اید.\n      این تعداد نردبان از اعتبار شما کاسته خواهد شد.",
                        ladderSuccess: "{numOfPosts} آگهی شما نردبان شد.",
                        doLadder: "نردبان کن",
                        subscriptionTitle: "وضعیت و خرید آگهی و نردبان",
                        payment: "پرداخت",
                        careersSubCategories: "زیردسته‌های استخدام و کاریابی",
                        submitNavTitle: "ثبت آگهی در پنل",
                        buyNewPostsPackage: "بستهٔ آگهی جدید بخرید",
                        buyPostsPackage: "خرید بستهٔ آگهی",
                        yourQuotaExceeded: "سهمیهٔ فعلی ثبت آگهی در پنل شما به پایان رسیده است.\n      با خرید بستهٔ آگهی جدید می‌توانید آگهی‌های فعال پنل خود را افزایش دهید.",
                        supportTitle: "تماس با پشتیبانی",
                        supportText: "در صورت وجود هرگونه سؤال یا ابهام، در تمامی ساعت‌های شبانه‌روز و روزهای هفته می‌توانید با ما در ارتباط باشید.\n برای ارتباط با ما با شمارهٔ {phone} تماس بگیرید.",
                        noPosts: "هیچ آگهی‌ای در پنل شما ثبت نشده‌است.\n       یک آگهی ثبت کنید.",
                        noPostsAction: "ثبت آگهی در دیوار",
                        purchasePost: "خرید بستهٔ آگهی",
                        purchaseLadder: "خرید بستهٔ نردبان",
                        purchasePostAndLadder: "خرید بستهٔ آگهی و نردبان",
                        yourAccountConfirmed: "حساب شما تأیید شد",
                        youCanStart: "می‌توانید شروع به کار کنید و از امکانات پنل استخدام دیوار بهره‌مند شوید.\n      با کلیک روی شروع به کار، {0} از پنل استخدام دیوار را می‌پذیرم.",
                        termsAndConditions: "قوانین و شرایط استفاده",
                        start: "شروع به کار",
                        welcomeToEmployerPanel: "به پنل استخدام خوش‌ آمدید."
                    },
                    users: {searchName: "جستجوی نام کاربر", delete: "حذف کاربر", yesDelete: "بله، حذف کن", add: "اضافه کردن کاربر", edit: "ویرایش اطلاعات کاربر", management: "مدیریت کاربران پنل", areYouSureDelete: "با حذف این کاربر، تمام آگهی‌های او از پنل استخدام حذف می‌شود. آیا از حذف کاربر مطمئن هستید؟", completelyDeleted: "کاربر و تمام آگهی‌های او حذف شد.", welcome: "خوش آمدید", welcomeToBusiness: "شما به پنل استخدام «{businessName}» اضافه شدید و می‌توانید از امکانات و دسترسی‌های پنل برای مدیریت راحت‌تر آگهی‌ها استفاده کنید."},
                    profile: {documentsVerified: "مدارک کارفرما تأیید شده", title: "پروفایل کارفرما", activityArea: "حوزهٔ کار"},
                    apply: {youAlreadyAppliedForPost: "قبلاً برای این آگهی رزومه ارسال کرده‌اید و ارسال دوباره امکان‌پذیر نیست.", request: "ارسال رزومه", requestIsNew: "ارسال رزومه (جدید)", applications: "رزومه‌های دریافتی", applicantInfo: "رزومهٔ کارجو", applicationsForPost: "رزومه‌های آگهی", youCantSeeThis: "شما نمی‌توانید رزومهٔ کارجو را مشاهده کنید", telephone: "تلفن"}
                }
            }), {angoolak: {submitButton: "درخواست", placeholder: "لینک را وارد کنید", customWidgetPlaceholder: "add custom widget: {\n  widget_list: [{...}]\n}", fetchWidgetFromAPI: "گرفتن ویجت از api", createYourOwnWidget: "ساختن ویجت به شکل دستی", feedback: {loggedInWithSpecificNumber: "با شماره {0} لاگین شدید", successMessage: "مثلا اطلاعات وارد شده با موفقیت ثبت شد.", canNotLoginWithSameNumber: "در حال حاضر با همین شماره {0} لاگین هستی"}, debugToken: {placeholder: "توکن دیباگ", saveButton: "ذخیره", removeButton: "حذف", enterToken: "توکن دیباگ خود را وارد کنید"}, sidebar: {flags: "فیچر فلگ‌ها", debugToken: "توکن دیباگ", widget: "ویجت", schema: "اسکیما", listOfTestNumbers: "لیست شماره های تستی", webWidgets: "لیست ویجت های وب"}}}), {
                deletePost: {confirmText: "آیا از حذف این آگهی مطمئن هستید؟", deleteNotAllowedText: "امکان حذف این آگهی وجود ندارد.", deletePost: "حذف آگهی", postWillRemove: "درخواست «حذف آگهی» ثبت شد. آگهی شما حداکثر تا ۲ ساعت دیگر حذف می‌شود."},
                deletePostReason: {specifyDeleteReason: "علت حذف آگهی را مشخص کنید."}
            }), {a11y: {a11ySatisfaction: "آیا از دسترسی‌پذیری وب‌سایت دیوار رضایت دارید؟", a11yFeedback: "بازخورد دسترسی‌پذیری", satisfied: "بله، رضایت دارم", notSatisfied: "خیر، رضایت ندارم", alt: {bannerAds: "بنر تبلیغاتی", captcha: "متن موجود در تصویر را وارد کنید.", divarLogo: "نشان دیوار", divarHomePage: "صفحه‌ اصلی دیوار", enamadLogo: "نشان نماد تجارت الکترونیکی", ecunionLogo: "نشان اتحادیه کشوری کسب‌و‌کارهای مجازی", imageNumber: "تصویر شماره {0}", samandehiLogo: "نشان ملی ثبت رسانه‌های دیجیتال"}, label: {bookmark: "نشان کردن", postNote: "یادداشت گذاری", share: "اشتراک گذاری", deleteNote: "حذف کردن یادداشت"}, search: {noResultFound: "پیشنهادی یافت نشد", numberOfFoundedResults: "{0} پیشنهاد یافت شد"}, map: {removeLocation: "پاک کردن نشانگر موقعیت آگهی", zoomIn: "بزرگ‌نمایی نقشه", zoomOut: "کوچک‌‌نمایی نقشه", myLocation: "انتخاب موقعیت فعلی شما", districtUpdated: "محله شما آپدیت شد"}}}), {
                pwa: {
                    install: "نصب وب‌اپ",
                    guide: "راهنمای وب‌اپلیکیشن",
                    description: "وب‌اپلیکیشن یا PWA دیوار سرویسی است که نصب آن، استفاده از دیوار را بدون نیاز به دانلود اپلیکیشن و به‌روز‌رسانی و تنها با کلیک روی آیکون آن فراهم می‌کند. در نسخهٔ وب‌اپلیکیشن نیازی به دانلود و به‌روزرسانی نیست و کاربران iOS و اندروید با دسترسی‌ به آیکون اپلیکیشن در کنار سایر اپ‌های موبایل خود می‌توانند از آن استفاده کنند.",
                    guides: {first: "۱. در نوار پایین روی دکمهٔ {0} {1} بزنید.", second: "۲. در منوی باز شده، گزینهٔ {0} {1} را انتخاب کنید.", third: "۳. در قسمت بالا روی دکمهٔ {0} بزنید."}
                }
            }), {sheba: {shebaNumber: "شمارهٔ شبا", editShebaNumber: "تغییر شمارهٔ شبا", bankAccountInfo: "اطلاعات حساب بانکی", shebaNumberPlaceholder: "شمارهٔ شبا بدون IR", wrongShebaNumberError: "شمارهٔ شبای وارد شده اشتباه است. شماره‌ی شبا را مانند مثال وارد کنید.", successfullySaved: "اطلاعات شما با موفقیت ثبت شد.", confirmationCode: "کد تأیید", enterConfirmationCode: ".کد تأیید ارسال شده به شماره {0} را وارد کنید", successfullyReturnMoneyDescription: "وجه مورد نظر به حساب شما بازگشت داده خواهد شد.", returnMoneyDescription: "برای بازگشت وجه, لطفاً شماره شبا خود را وارد کنید.\nمثال: ...IR1234567", fullNamePlaceholder: "نام و نام خانوادگی", wrongFullNameError: "نام دارنده حساب را کامل وارد کنید. مانند: جعفر جعفریان", fullNameTitle: "نام و نام خانوادگی دارنده حساب"}}), {
                safety: {
                    title: "دیوار بدون مزاحمت",
                    harassment: {title: "چه رفتاری مزاحمت محسوب می‌شود؟", description: "موارد زیر مصداق‌های مهم مزاحمت هستند:", subtitle: "هرگونه رفتاری که با هدفی غیر از انجام معامله انجام شود نوعی از مزاحمت را برای کاربران ایجاد می‌کند.", sendingNSFW: "ارسال عکس، فیلم یا هرگونه محتوای نامناسب و غیراخلاقی", askingPersonalInfo: "پرسش‌های خصوصی یا پیشنهاد‌های نامتعارف", insult: "فحاشی و توهین یا تهدید", spam: "تبلیغات، گدایی و هرگونه صحبت‌های نامربوط به معامله"},
                    divarRule: {title: "نقش دیوار در جلوگیری از مزاحمت", description: "یکی اهداف مهم در دیوار به حداقل رساندن مواجهه کاربران به خصوص زنان با هرگونه آزار و مزاحمت است. آگاه‌سازی کاربران، ارائه ابزارهای مواجهه با مزاحمت مثل گزارش و مسدودی و استفاده از تکنولوژی‌های روز از جمله هوش مصنوعی برای تشخیص سریع‌تر تخلف‌ها، بخشی از اقدام‌های دیوار برای جلوگیری از مزاحمت هستند."},
                    meeting: {title: "امنیت در ملاقات حضوری", description: "در صورتی که برای انجام معامله نیاز به ملاقات حضوری دارید حتما ایمنی خود را اولویت قرار دهید و موارد زیر را رعایت کنید:", place: "مکان مناسب: همیشه در یک مکان عمومی، با نور کافی و با حضور مردم دیدار کنید. کافه‌ها، مراکز خرید یا حتی پارکینگ یک فروشگاه شلوغ، انتخاب‌های خوبی هستند.", accompaniment: "داشتن همراه: در صورت امکان با یک همراه به دیدار فرد مقابل بروید. ", informOthers: "مطلع کردن دیگران: یک فرد قابل اعتماد را از زمان، مکان و جزئیات معامله‌تان مطلع کنید. بهتر است اطلاعات تماس فرد مقابل را هم با او به اشتراک بگذارید.", privateData: "حفاظت از اطلاعات شخصی: از اشتراک اطلاعات شخصی حساس مانند آدرس منزل پرهیز کنید."},
                    encounterTodos: {title: "در صورت مواجهه شدن با مزاحمت چه کنم؟", report: "گزارش: در صورت مواجهه با مزاحمت می‌توانید رفتار کاربر را گزارش کنید تا ادامهٔ فعالیت‌های او در دیوار محدود شود. گزارش‌ شما کمک می‌کند کاربران کم‌تری با رفتار ناخوشایند این کاربر مواجه شوند. ", block: "مسدودی: برای جلوگیری از تعاملات بیشتر با کاربر متخلف می‌توانید او را مسدود کنید. ", legalAction: "شکایت قضایی: در صورتی که مایل به پیگیری قضایی هستید می‌توانید شکایت خود در مراجع قضایی ثبت کنید. دیوار نیز نهایت همکاری را با مراجع قضایی برای پیگیری شکایت شما خواهد داشت."},
                    infos: {title: "آنچه باید دربارهٔ مزاحمت بدانیم", subtitle: "آگاهی، اولین گام مقابله با مزاحمت"},
                    howToImproveSafety: "با چه ابزارهایی به امنیت و سلامت خودم و کاربران دیوار کمک کنم؟",
                    safetyFeatures: {block: {title: "مسدود کردن در چت", description: "دکمهٔ مسدود کردن در بالای تمام مکالمات چت در دسترس است. با مسدود کردن کاربر هیچ پیام دیگری از او دریافت نمی‌کنید."}, report: {title: "گزارش در چت", description: "برای ثبت گزارش در چت، روی نشان «سه‌نقطه» که در گوشهٔ راست بالای مکالمه قرار دارد کلیک کنید و گزینهٔ «گزارش تخلف» را انتخاب کنید."}, reportPost: {title: "گزارش در آگهی", description: "برای ثبت گزارش در آگهی، بازخورد خود دربارهٔ آگهی را ثبت کنید و گزینهٔ «محتوای آگهی غیرقانونی یا غیراخلاقی است» را انتخاب کنید."}, anonymosCall: {title: "تماس ناشناس", description: "تماس ناشناس برای جلوگیری از مزاحمت، شمارهٔ شما را نمایش نمی‌دهد و کاربران با شمارهٔ واسطه با شما تماس می‌گیرند."}},
                    newestSafetyFeatures: {title: "جدیدترین امکانات دیوار برای حفظ امنیت و سلامت کاربران", hiddenChat: {title: "مکالمه‌های افراد مشکوک", description: "تشخیص مکالمه‌های ناخوشایند و نامربوط به معامله توسط هوش مصنوعی", releaseDate: "پاییز ۱۴۰۲"}, anonymosCall: {title: "تماس ناشناس دیوار", description: "برقراری تماس از طریق شماره‌های واسطهٔ دیوار", releaseDate: "بهار ۱۴۰۲"}},
                    safetyQuiz: {ready: "برای مقابله با مزاحمت آماده‌ای؟", testYourSelf: "خودت رو آزمایش کن!", harassmentConfrontationTest: "آزمون مقابله با مزاحمت"}
                }
            }), {
                safetyTrust: {
                    title: "مقابله با مزاحمت و کلاهبرداری",
                    safetyTrustMetaTitle: "گزارش کلاهبرداری و مزاحمت",
                    safetyTrustMetaDescription: "در این بخش می‌توانید هر گونه کلاهبرداری و مزاحمت را گزارش کنید",
                    harassmentMetaTitle: "گزارش مزاحمت",
                    harassmentMetaDescription: "در این بخش می‌توانید هر گونه مزاحمت را گزارش کنید",
                    description: "اگر به آگهی یا چت مربوط به کلاهبرداری دسترسی دارید، لطفاً برای پیگیری سریع‌تر، همان‌جا گزارش خود را ثبت کنید.\n\nدر صورت عدم دسترسی به آگهی یا چت، از این‌جا گزارش کلاهبرداری را ثبت کنید.",
                    actionButton: "ثبت گزارش کلاهبرداری",
                    divarWithoutHarassment: "دیوار بدون مزاحمت",
                    divarWithoutScam: "دیوار بدون کلاهبرداری",
                    howToPreventHarassment: "چطور جلوی مزاحمت را بگیرم؟",
                    howToPreventScam: "چطور جلوی کلاهبرداری را بگیرم؟",
                    reportScam: "گزارش کلاهبرداری و رفتار مشکوک",
                    reportHarassment: "گزارش مزاحمت",
                    reportViolation: "گزارش تخلف",
                    submitHarassmentReport: "ثبت گزارش مزاحمت",
                    reportDivarChatHint: "راهنمای گزارش در چت دیوار",
                    reportDivarPostHint: "راهنمای گزارش در آگهی",
                    hint: "راهنما",
                    reportDivarPost: "گزارش در آگهی",
                    reportDivarChat: "گزارش در چت دیوار",
                    behaviorConsideredHarassment: "چه رفتاری مزاحمت محسوب می‌شود؟",
                    behaviorConsideredHarassmentDescription: "هرگونه رفتاری که با هدفی غیر از انجام معامله انجام شود نوعی از مزاحمت را برای کاربران ایجاد می‌کند. موارد زیر مصداق‌های اصلی مزاحمت هستند: \n - ارسال عکس، فیلم یا هرگونه محتوای نامناسب و غیراخلاقی \n - پرسش‌های خصوصی یا پیشنهاد‌های نامتعارف \n - فحاشی، توهین یا تهدید \n - تبلیغات یا هرگونه صحبت‌های نامربوط به معامله",
                    HowToreportHarassment: "چطور مزاحمت را گزارش کنم؟",
                    moreDetailedInvestigation: "برای بررسی دقیق‌تر گزارش مزاحمت، لطفاً آن را در چت یا آگهی ثبت کنید.",
                    noAccessToChatOrPost: "به آگهی یا چت کاربر دسترسی ندارید؟",
                    noAccessToChatOrPostDescription: "اگر به آگهی یا چت کاربر متخلف دسترسی ندارید، گزارشتان را همین‌جا ثبت کنید.",
                    submitReport: "ثبت گزارش",
                    reportSubmitted: "گزارش شما ثبت شد. دیوار فعالیت کاربرانی را که زیاد گزارش شده‌اند محدود می‌کند.",
                    whoCausedHarassment: "چه کسی مزاحمت ایجاد کرده است؟",
                    whereDidHarassmentHappened: "کجا مزاحمت ایجاد کرده است؟",
                    whichTypeHappened: "با چه نوع مزاحمتی مواجه شده‌اید؟",
                    chooseClosestAnswer: "لطفاً نزدیک ترین گزینه به اتفاقی که برای شما پیش آمده است را انتخاب کنید.",
                    postOwner: "صاحب آگهی",
                    postVisiter: "بازدیدکنندهٔ آگهی خودم",
                    inChat: "در چت دیوار",
                    inSms: "در تماس تلفنی، پیامک یا سایر پیام‌رسان‌‌ها",
                    inSecureCall: "در تماس ناشناس دیوار",
                    inPerson: "مزاحمت حضوری",
                    etc: "سایر موارد",
                    improperConversation: "مکالمهٔ غیراخلاقی، خصوصی یا نامتعارف",
                    rudeness: "فحش، توهین یا تهدید",
                    advertisement: "تبلیغات",
                    shareNumber: "دادن شمارهٔ من به کاربران دیوار بدون اجازه",
                    additionalInfo: "اطلاعات تکمیلی",
                    harasserInfo: "مشخصات کاربر مزاحم",
                    additionalInfoDescription: "در صورت نیاز با جزئیات توضیح دهید چه مشکلی پیش آمده است تا کارشناس بتوانند گزارش‌تان را دقیق‌تر بررسی کند.",
                    harasserInfoDescription: "برای پیگیری دقیق‌تر گزارش، هر چه از کاربر مزاحم می‌دانید، وارد کنید.\n(مثال: شمارهٔ موبایل، نام کاربری در چت، عنوان آگهی و...)",
                    harassment: "مزاحمت",
                    reportType: "نوع گزارش: {type} {where} توسط {harasser}",
                    placeholder: "توضیحات (اختیاری)"
                }
            }), {
                premiumPanel: {
                    introduction: {title: "معرفی دیوار حرفه‌ای", seoTitle: "دیوار حرفه‌ای: رونق کسب‌وکار با مدیریت پیشرفته و صفحه اختصاصی", seoDescription: "با دیوار حرفه‌ای، کسب‌وکار خود را رونق دهید. از امکانات صفحه اختصاصی، افزودن همکاران، و کیف پول اشتراکی برای مدیریت بهتر آگهی‌ها و مشتریان بهره‌مند شوید."},
                    title: "دیوار حرفه‌ای",
                    verified: "تأیید هویت شده",
                    invitations: "دعوت‌نامه‌ها",
                    selectBusiness: "انتخاب کسب‌و‌کار",
                    activateDivarPro: "فعال‌سازی دیوار حرفه‌ای",
                    managePosts: "مدیریت آگهی‌ها",
                    walletAndPayment: "کیف پول و پرداخت",
                    agentManagement: "مدیریت همکاران",
                    agent: "همکار",
                    owner: "مالک",
                    noBusiness: "کسب‌و‌کاری وجود ندارد.",
                    noBusinessDescription: "شما در حال حاضر عضو هیچ کسب‌و‌کار فعالی نیستید. می‌توانید کسب‌و‌کار جدیدی را در دیوار حرفه‌ای بسازید و یا از دیوار حرفه‌ای خارج شوید.",
                    addAgent: "اضافه کردن همکار",
                    deactivePro: "غیرفعال‌سازی دیوار حرفه‌ای",
                    deactivatedSuccessfuly: "حساب شما با موفقیت غیرفعال شد.",
                    agentDetail: "اطلاعات همکار",
                    UsageReport: "گزارش فعالیت",
                    manageBusiness: "مدیریت کسب‌و‌کار",
                    editBusiness: "ویرایش کسب‌و‌کار",
                    helpAndSupport: "راهنما و پشتیبانی",
                    createNewBusiness: "ساخت کسب‌و‌کار جدید",
                    editAgent: "ویرایش همکار",
                    submitFirstPost: "اولین آگهی خود را ثبت کنید.",
                    editData: "ویرایش اطلاعات",
                    previousPage: "صفحه قبلی",
                    allocateQuota: "تخصیص سهمیه",
                    panelBusinessesError: "خطایی در نمایش پنل پیش آمده است.",
                    businessPage: "صفحهٔ اختصاصی",
                    profileVerification: "احراز پروفایل",
                    proInvitation: "دعوت‌نامهٔ دیوار حرفه‌ای",
                    roleAndPhoneNumber: "{phoneNumber} | {role}",
                    publicLandingDescription: "مشاهده و خرید انواع محصولات در بین {businessName}. از جدیدترین {businessName} مطلع شوید و محصولات با کیفیت را به صورت مستقیم خریداری کنید.",
                    useUsageReportInApp: "برای استفاده از گزارش فعالیت لطفا به اپلیکیشن مراجعه کنید."
                }
            }), {
                about: {
                    aboutDivar: " دربارهٔ دیوار ",
                    metaTitle: " دربارهٔ دیوار ",
                    description: "دیوار از ۲۱ تیر ۱۳۹۱ با هدف خرید و فروش بدون واسطهٔ آنلاین آغاز به کار کرد. امتیاز برند دیوار توسط شرکت «آگه پردازان هوشمند» (سهامی خاص) در تمامی مراجع قانونی ثبت شده است.",
                    metaDescription: "دیوار از ۲۱ تیر ۱۳۹۱ با هدف خرید و فروش بدون واسطهٔ آنلاین آغاز به کار کرد. امتیاز برند دیوار توسط شرکت «آگه پردازان هوشمند» (سهامی خاص) در تمامی مراجع قانونی ثبت شده است.",
                    divarPartners: "همکاران تجاری دیوار",
                    readMore: "بیشتر بخوانید",
                    allCareers: "همهٔ فرصت‌های شغلی",
                    contactSupport: "ارتباط با پشتیبانی",
                    contactDivar: "ارتباط با دیوار",
                    cyberPoliceWebsite: "سایت پلیس فتا",
                    careersDescription: "اینجا دیوار است؛ جایی برای رشد، یادگیری و خلق ایده‌های جدید. اینجا در کنار هم برای چالش‌ها راه‌حل پیدا می‌کنیم، تجربه کسب می‌کنیم و بر سبک زندگی میلیون‌ها نفر تاثیر‌گذاریم. برای پیوستن به دیوار، می‌توانید موقعیت شغلی متناسب با توانمندی‌های خود را در این صفحه پیدا کرده و برای همکاری اقدام کنید.",
                    contactDescription: "مشکلات دیوار، انتقاد و پیشنهاد خود را با پشتیبانی دیوار در میان بگذارید. همچنین در صورت ایجاد مزاحمت برای شما، اطلاعات تماس پلیس فتای محل سکونت خود را از سایت پلیس فتا دریافت و موضوع را از آن راه پیگیری کنید.",
                    supportPhoneText: "شمارهٔ تماس پشتیبانی: ",
                    legalAddress: "آدرس پستی: تهران، اوین، بلوار دانشجو، ساختمان دانشگاه شهید بهشتی، پارک علم و فناوری شهید بهشتی، طبقهٔ منفی سه، واحد ۸",
                    legalPostalCode: "صندوق پستی: ۶۹۷۵۴-۱۹۸۳۹",
                    postalCode: "صندوق پستی: ۷۵۵۷۳-۱۹۶۹۷",
                    addressDescription: "تیم‌های فنی ما در این آدرس هستند، اما متأسفانه نمی‌توانیم پذیرای مراجعان حضوری باشیم.",
                    joinDivar: "دیواری شو",
                    partners: {
                        karnameh: {
                            name: "کارنامه",
                            description: "کارنامه با هدف خلق تجربه کاربری بهتر در خرید و فروش خودرو و به عنوان یک سرویس مکمل دیوار، با ارائه سرویس‌های کارشناسی خودرو در محل و فروش سفارشی آغاز به کار کرد.",
                            details: "کارنامه از پاییز ۱۳۹۸ با هدف خلق تجربه کاربری بهتر در خرید و فروش خودرو و به عنوان یک سرویس مکمل دیوار در حوزه خودرو، کار خود را آغاز کرد. این سرویس در نظر دارد تا به دستیار مطمئن ایرانیان در خرید و فروش خودرو تبدیل شود و خدمات کارشناسی خودرو در محل و فروش سفارشی را به کاربران ارائه می‌کند.\nدر سرویس فروش سفارشی کارنامه، بعد از کارشناسی فنی و بدنه و تخمین قیمت، تمامی فرایندهای درج و انتشار آگهی، پاسخگویی به خریداران، هماهنگی بازدید و مشاوره جهت عقد قرارداد فروش خودرو را در مدت ۵ تا ۷ روز برای کاربران انجام می‌دهد.\nاز دیگر سرویس‌های کارنامه می‌توان به «خرید سفارشی» نیز اشاره کرد که بسته به نیاز و بودجه مشتریان، خودروهای کارشناسی شده مناسب به آنها پیشنهاد شده تا فرآیند خرید خودرو بسیار ساده‌تر از قبل باشد.\nکارنامه هم مانند همه مجموعه‌های نوآور، فرایندهای توسعه را در دستور کار دارد و به‌زودی خدمات دیگری نیز به مجموعه خدمات خود اضافه خواهد کرد."
                        }, pishgaman: {name: "پیشگامان", description: "پیشگامان، به‌عنوان یک شرکت مستقل در کنار دیوار همکاری می‌کند و به‌نوعی بازوی اصلی پشتیبانی و ارتباط نزدیک با کاربران محسوب می‌شود.", details: "شریک تجاری دیگر دیوار، مسئولیت نظارت بر آگهی و بخشی از پشتیبانی مشتریان را برعهده دارد. پیشگامان، به‌عنوان یک شرکت مستقل در کنار دیوار همکاری می‌کند و به‌نوعی بازوی اصلی پشتیبانی و ارتباط نزدیک با کاربران محسوب می‌شود.\nنظارت کامل بر آگهی‌های دیوار و مدیریت آن‌ها، مسئولیت اصلی شرکت پیشگامان است. این شرکت هم برنامه‌های توسعه‌ای و افزایش خدمات را در دستور کار دارد و به‌زودی، سرویس‌های جدیدی را به مجموعه خود اضافه می‌کند."}
                    },
                    details: {
                        divarHistory: "تاریخچه‌ٔ دیوار",
                        description: "دیوار فعالیت خود را از ۲۱ تیر ۱۳۹۱ و با هدف ارائه بستری برای خرید و فروش بی‌واسطه در ایران شروع کرد. برند دیوار امروز تحت مالکیت شرکت «آگه پردازان هوشمند» فعالیت می‌کند. این شرکت در سال ۱۳۹۱ و با هدف سازمان‌دهی و توسعه بهتر خدمات آگهی آنلاین راه‌اندازی شد و در دستهٔ شرکت‌های دانش‌بنیان نوآور قرار گرفت.\n\nخدمات ثبت و مرور آگهی‌های دیوار در تمامی پلتفرم‌های پرطرفدار اعم از اندروید، iOS و وب در دسترس کاربران قرار دارد. اپلیکیشن اندرویدی دیوار در پایان شهریور ۱۴۰۱ بیشترین آمار دانلود و نصب فعال را در کشور پس از اپلیکیشن بازار با بیش از ۲۴.۴ میلیون نصب فعال در گوشی‌های اندرویدی به خود اختصاص داده است. خدمات انتشار و جست‌وجوی آگهی در دیوار درحال‌حاضر در بیش از ۳۷۰ شهر کشور در اختیار کاربران قرار دارد. آگهی‌ها در دسته‌های متنوعی از املاک، وسایل نقلیه و کالای دیجیتال تا استخدام و خدمات کسب‌وکار منتشر می‌شوند.\nدیوار از سال ۱۳۹۹ در راستای کارآمدی بیشتر و ارائه خدمات به کسب‌وکارها، با ایجاد تغییراتی، سرویس‌هایی اختصاصی را برای کسب‌وکارهای فعال در پلتفرم خود راه‌اندازی کرد تا صاحبان مشاغل، با سرعت و آسودگی بیشتری فرآیند فروش کالا و خدمات خود را در صفحه‌های اختصاصی انجام دهند. از این خدمات در حال حاضر می‌توان به پنل آژانس و مشاوران املاک، پنل اختصاصی برای نمایشگاه‌های خودرو و پنل فروشگاهی دیوار اشاره کرد. فروشندگان کالا می‌توانند روی دیوار صاحب شعبه‌ای آنلاین و اختصاصی شوند و به مجموعه مشتریان چند ده میلیونی دیوار دسترسی داشته باشند.\nدیوار با بهره‌مندی از زیرساخت قوی و فناوری‌های پیشرفته، فرآیندهای توسعه و بهبود خدمات خود را به‌صورت ادامه‌دار در دستور کار دارد. تیم‌های فنی و پشتیبانی دیوار با استفاده از ابزارهایی همچون زیرساخت ابری، یادگیری ماشینی، پردازش تصویر، پردازش زبان طبیعی و دیگر فناوری‌های به‌روز، فرآیند انتشار، جست‌وجو، فیلتر کردن و ارتباط در آگهی‌ها را روز‌به‌روز برای کاربران بهبود می‌بخشند.\nفرآیند توسعه و بهینه‌سازی خدمات، جزو جدانشدنی دیوار است. ما همیشه در تلاش هستیم تا در مسیر حفظ جایگاه بزرگ‌ترین مرجع نیازمندی‌های آنلاین در ایران، با توجه به بازخوردهای کاربران و بررسی‌های دائمی، خدمات جدیدتر و بهتری را به مجموعه خود اضافه کنیم.",
                        metaTitle: "تاریخچهٔ دیوار: گذشته‌ٔ دیوار را دقیق‌تر ببینید",
                        metaDescription: "دیوار فعالیت خود را از ۲۱ تیر ۱۳۹۱ و با هدف ارائه بستری برای خرید و فروش بی‌واسطه در ایران شروع کرد. برند دیوار امروز تحت مالکیت شرکت «آگه پردازان هوشمند» فعالیت می‌کند. این شرکت در سال ۱۳۹۱ و با هدف سازمان‌دهی و توسعه بهتر خدمات آگهی آنلاین راه‌اندازی شد و در دستهٔ شرکت‌های دانش‌بنیان نوآور قرار گرفت.\n\nخدمات ثبت و مرور آگهی‌های دیوار در تمامی پلتفرم‌های پرطرفدار اعم از اندروید، iOS و وب در دسترس کاربران قرار دارد. اپلیکیشن اندرویدی دیوار در پایان شهریور ۱۴۰۱ بیشترین آمار دانلود و نصب فعال را در کشور پس از اپلیکیشن بازار با بیش از ۲۴.۴ میلیون نصب فعال در گوشی‌های اندرویدی به خود اختصاص داده است. خدمات انتشار و جست‌وجوی آگهی در دیوار درحال‌حاضر در بیش از ۳۷۰ شهر کشور در اختیار کاربران قرار دارد. آگهی‌ها در دسته‌های متنوعی از املاک، وسایل نقلیه و کالای دیجیتال تا استخدام و خدمات کسب‌وکار منتشر می‌شوند.\nدیوار از سال ۱۳۹۹ در راستای کارآمدی بیشتر و ارائه خدمات به کسب‌وکارها، با ایجاد تغییراتی، سرویس‌هایی اختصاصی را برای کسب‌وکارهای فعال در پلتفرم خود راه‌اندازی کرد تا صاحبان مشاغل، با سرعت و آسودگی بیشتری فرآیند فروش کالا و خدمات خود را در صفحه‌های اختصاصی انجام دهند. از این خدمات در حال حاضر می‌توان به پنل آژانس و مشاوران املاک، پنل اختصاصی برای نمایشگاه‌های خودرو و پنل فروشگاهی دیوار اشاره کرد. فروشندگان کالا می‌توانند روی دیوار صاحب شعبه‌ای آنلاین و اختصاصی شوند و به مجموعه مشتریان چند ده میلیونی دیوار دسترسی داشته باشند.\nدیوار با بهره‌مندی از زیرساخت قوی و فناوری‌های پیشرفته، فرآیندهای توسعه و بهبود خدمات خود را به‌صورت ادامه‌دار در دستور کار دارد. تیم‌های فنی و پشتیبانی دیوار با استفاده از ابزارهایی همچون زیرساخت ابری، یادگیری ماشینی، پردازش تصویر، پردازش زبان طبیعی و دیگر فناوری‌های به‌روز، فرآیند انتشار، جست‌وجو، فیلتر کردن و ارتباط در آگهی‌ها را روز‌به‌روز برای کاربران بهبود می‌بخشند.\nفرآیند توسعه و بهینه‌سازی خدمات، جزو جدانشدنی دیوار است. ما همیشه در تلاش هستیم تا در مسیر حفظ جایگاه بزرگ‌ترین مرجع نیازمندی‌های آنلاین در ایران، با توجه به بازخوردهای کاربران و بررسی‌های دائمی، خدمات جدیدتر و بهتری را به مجموعه خود اضافه کنیم.",
                        partnersDescription: "دیوار در مسیر توسعه و گسترش خدمات و همچنین برطرف کردن قسمتی از نیازهای عملیاتی خود، سرویس‌های جدیدی را در قالب شرکت‌های جدید ارائه نماید. دیوار در کنار کارنامه و پیشگامان، مجموعه‌ای از خدمات کاربردی را به کاربران خود ارائه می‌دهد.",
                        responsibilityTitle: "مسئولیت اجتماعی دیوار",
                        responsibilityDescription: "دیوار بستری برای فعالیت ۵۳ میلیون گوشی یکتا در سال ۱۴۰۰ بوده است. انتشار روزانهٔ بیش از ۳۸۳ هزار آگهی و ۱۵۲ میلیون بازدید در روز، دیوار را به یکی از پلتفرم‌های تاثیرگذار در بستر آنلاین کشور تبدیل کرده است.\nاز این رو، دیوار صرفاً یک کسب‌وکار ساده نیست و تمام تلاش خود را می‌کند تا بتواند نقش و مسئولیت خود را در قبال کاربران، جامعه و محیط زیست ایفا کند. علاوه بر این، تمام افرادی که به دیوار می‌پیوندند می‌توانند در تعریف و اجرای پروژه‌های مرتبط با مسئولیت اجتماعی نقش داشته باشند. اقداماتی از جمله کمک به مؤسسات مردم‌نهاد برای حفظ و حراست از جنگل‌های زاگرس، ایجاد امکان گزارش کاربر در چت دیوار برای افزایش امنیت زنان، ایجاد امکان استفاده از اپلیکیشن برای افراد کم‌بینا و حذف آگهی‌های مربوط به خرید و فروش گونه‌های ممنوعهٔ‌ جانوری، تنها نمونه‌هایی از فعالیت‌های دیوار در راستای مسئولیت اجتماعی است."
                    }
                }
            }), {overUsage: {title: "از تاریخ ۱ تیر ۱۴۰۳ سهمیهٔ ثبت آگهی رایگان در دیوار از ماهانه به سالانه تغییر کرده است. تعداد آگهی رایگان سالانه در هر دسته متفاوت است.", link: "سهمیهٔ رایگان هر دسته", metaTitle: "دیوار - سهمیهٔ رایگان هر دسته", metaDescription: "سهمیهٔ ثبت آگهی رایگان در دیوار از ماهانه به سالانه تغییر کرده است. تعداد آگهی رایگان سالانه در هر دسته متفاوت است.", selectCity: {title: "شهری انتخاب نشده است.", description: "برای دیدن سهمیهٔ ثبت آگهی رایگان، شهر خود را انتخاب کنید.", button: "انتخاب شهر"}, empty: {title: "محتوایی برای نمایش نیست.", description: "سهمیهٔ ثبت آگهی خالی است. "}}}), {multiCity: {allCities: "همه‌ی شهرها", allCitiesOfProvince: "همه‌ی شهرهای {0}", tehran: "تهران"}}), {
                bookmarks: {
                    allPostsAndNotes: "آگهی‌ها و یادداشت‌ها",
                    searches: "جستجوها",
                    bookmarks: "نشان‌ها",
                    postsTabOnBoardingText: "آگهی‌های نشان شده و یادداشت‌های خود را در این صفحه می‌بینید.",
                    searchesTabOnBoardingText: "جستجوهای ذخیره‌شدهٔ خود را در این صفحه می‌بینید.",
                    bookmarksTabOnBoardingText: "آگهی‌ها و جستجوهایی که نشان کرده‌اید را می‌توانید در این صفحه ببینید."
                }
            }), {searchAssistant: {onboardingTooltipText: "دستیار خرید (آزمایشی)", title: "دستیار خرید (آزمایشی)", chatPlaceholder: "پیام خود را بنویسید...", send: "ارسال", sendDisabled: "ارسال(غیرفعال)", errorReplying: "خطا در ارسال پیام", trial: "آزمایشی", waitUntilDone: "لطفا تا اتمام پاسخ صبر کنید...", waitUntilYourMessageSent: "لطفا تا ارسال پیام خود صبر کنید...", restart: "شروع مجدد", restartDescription: "با شروع مجدد مکالمه، پیام های فعلی از دسترس شما خارج شده و از حافظه دستیار خرید پاک می شود.", scrollToBottom: "برو به پایین صفحه", wasThisMessageHelpful: "این پیام مفید بود؟", errorSendingFeedback: "خطا در ارسال نظر"}}), {unsafeCitySelector: {iran: "کل ایران", chooseAtLeastOneCityOrDistrict: "لطفاً حداقل یک شهر یا محله را انتخاب کنید.", searchCityAndDistrict: "جستجوی شهر و محله", wholeCity: "کل شهر {0}"}}), {
                hip: {
                    arcaptchaError: "متأسفانه خطایی پیش آمده است. لطفا این صفحه را ببندید و دوباره آن را باز کنید.",
                    captchaModal: {title: "برای دیدن اطلاعات آگهی‌گذار، روی مربع زیر بزنید", subtitle: "برای امنیت بیشتر حساب کاربری خود و جلوگیری از دستیابی ربات‌ها به اطلاعات کاربران، لطفاً روی مربع زیر بزنید، سپس به فعالیت خود ادامه دهید."},
                    tooManyCaptchaRetries: "بیش از ۱۰ بار برای حل چالش تصویری تلاش کرده‌اید. لطفاً چند دقیقهٔ دیگر دوباره تلاش کنید.",
                    retry: {title: "متأسفانه خطایی در بارگذاری اطلاعات پیش آمده است", description: "لطفاً دوباره صفحه را باز کنید.", retry: "بازگشت به آگهی"}
                }
            })
        })
    }
}]);
//# sourceMappingURL=per-localization-867.253746b1.desktop.js.map